aws_region            = "us-west-2"
vpc_cidr              = "10.0.0.0/16"
subnet_1_cidr         = "10.0.1.0/24"
subnet_2_cidr         = "10.0.2.0/24"
availability_zone_1   = "us-west-2a"
availability_zone_2   = "us-west-2b"
language              = "Tomcat"
instance_type         = "t3.micro"
